# Generated by Django 4.1.1 on 2023-06-24 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingrediente', '0001_initial'),
        ('componente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codReceta', models.CharField(max_length=50, unique=True, verbose_name='Código Receta')),
                ('nomReceta', models.CharField(max_length=50, verbose_name='Nombre Receta')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('estandar', models.CharField(max_length=50, verbose_name='Estandar')),
                ('preparacion', models.TextField(null=True, verbose_name='Preparación')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='RecetaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingrediente.ingrediente')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receta.receta')),
            ],
            options={
                'verbose_name': 'Receta-Ingrediente',
                'verbose_name_plural': 'Recetas-Ingredientes',
            },
        ),
        migrations.AddField(
            model_name='receta',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, through='receta.RecetaIngrediente', to='ingrediente.ingrediente', verbose_name='Ingredientes'),
        ),
        migrations.AddField(
            model_name='receta',
            name='nomComponente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='componente.componente', verbose_name='Nombre Componente'),
        ),
    ]
