# Generated by Django 4.1.1 on 2022-11-24 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('componente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codReceta', models.CharField(max_length=50, verbose_name='Cod Receta')),
                ('nomReceta', models.CharField(max_length=50, verbose_name='Nom Receta')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('estandar', models.CharField(max_length=50, verbose_name='Estandar')),
                ('consecutivo', models.CharField(max_length=50, verbose_name='Consecutivo')),
                ('fkcodComponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componente.componente', verbose_name='Cod Componente')),
            ],
        ),
    ]
