# Generated by Django 4.1.1 on 2022-11-30 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_tipousuario'),
        ('componente', '0001_initial'),
        ('ingrediente', '0001_initial'),
        ('receta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='consecutivo',
        ),
        migrations.AddField(
            model_name='receta',
            name='fkcodIngrediente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ingrediente.ingrediente', verbose_name='Código Componente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receta',
            name='super',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Supervisor', to='usuarios.usuario', verbose_name='Super'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receta',
            name='codReceta',
            field=models.CharField(max_length=50, verbose_name='Código Receta'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='fkcodComponente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componente.componente', verbose_name='Código Componente'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='nomReceta',
            field=models.CharField(max_length=50, verbose_name='Nombre Receta'),
        ),
        migrations.CreateModel(
            name='RecetaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingrediente.ingrediente', verbose_name='Ingrediente')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receta.receta', verbose_name='Nombre Receta')),
            ],
        ),
    ]
