# Generated by Django 4.1.2 on 2023-03-18 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0004_delete_recetadetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='estandar',
        ),
    ]
