# Generated by Django 4.1.2 on 2023-04-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0006_receta_estandar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='codReceta',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código Receta'),
        ),
    ]
