# Generated by Django 4.1.1 on 2023-06-06 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingrediente', '0008_alter_ingrediente_options'),
        ('receta', '0007_alter_receta_codreceta'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='codIngrediente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingrediente.ingrediente', verbose_name='Código ingrediente'),
        ),
    ]
