# Generated by Django 4.1.1 on 2023-03-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0007_receta_ingrediente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='ingrediente',
        ),
        migrations.AddField(
            model_name='receta',
            name='nomIngrediente',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Nombre Ingrediente'),
        ),
    ]
