# Generated by Django 4.1.1 on 2023-03-21 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingrediente', '0007_alter_ingrediente_estado'),
        ('receta', '0008_remove_receta_ingrediente_receta_nomingrediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='codIngrediente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ingrediente.ingrediente', verbose_name='Código Ingrediente'),
        ),
    ]
