# Generated by Django 4.1.1 on 2023-03-21 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0009_receta_codingrediente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='codIngrediente',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='nomIngrediente',
        ),
    ]
