# Generated by Django 4.1.1 on 2023-06-14 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0010_receta_nomcomponente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receta',
            options={'verbose_name': 'Receta', 'verbose_name_plural': 'Recetas'},
        ),
        migrations.AddField(
            model_name='receta',
            name='cantidadMateriaPrima',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de Materia Prima'),
        ),
        migrations.AddField(
            model_name='receta',
            name='costoTotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Total'),
        ),
    ]
