# Generated by Django 4.2.2 on 2023-06-22 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingrediente', '0008_alter_ingrediente_options'),
        ('receta', '0011_alter_receta_options_receta_cantidadmateriaprima_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='nomIngrediente',
        ),
        migrations.AlterField(
            model_name='receta',
            name='cantidadMateriaPrima',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad de Materia Prima'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='RecetaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingrediente.ingrediente')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receta.receta')),
            ],
            options={
                'verbose_name': 'Receta-Ingrediente',
                'verbose_name_plural': 'Recetas-Ingredientes',
            },
        ),
        migrations.AddField(
            model_name='receta',
            name='ingredientes',
            field=models.ManyToManyField(through='receta.RecetaIngrediente', to='ingrediente.ingrediente', verbose_name='Ingredientes'),
        ),
    ]
