# Generated by Django 4.2.2 on 2023-06-22 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0012_remove_receta_nomingrediente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='ingredientes',
            new_name='nomIngredientes',
        ),
    ]
