# Generated by Django 4.2.2 on 2023-06-22 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0013_rename_ingredientes_receta_nomingredientes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='nomIngredientes',
            new_name='codIngrediente',
        ),
    ]
