# Generated by Django 4.2.2 on 2023-06-22 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0014_rename_nomingredientes_receta_codingrediente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='codIngrediente',
            new_name='ingrediente',
        ),
    ]
