# Generated by Django 4.2.2 on 2023-06-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingrediente', '0008_alter_ingrediente_options'),
        ('receta', '0015_rename_codingrediente_receta_ingrediente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='ingrediente',
        ),
        migrations.AddField(
            model_name='receta',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, to='ingrediente.ingrediente', verbose_name='Ingredientes'),
        ),
    ]
