# Generated by Django 4.1.5 on 2023-01-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codListaPrecio', models.CharField(max_length=50, verbose_name='Cod Lista Precio')),
                ('nomListaPrecio', models.CharField(max_length=50, verbose_name='Nom Lista Precio')),
                ('tipoLista', models.CharField(max_length=50, verbose_name='Tipo Lista')),
            ],
        ),
    ]
