# Generated by Django 4.1.2 on 2023-03-17 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingrediente', '0007_alter_ingrediente_estado'),
        ('centroCostos', '0002_remove_centrocosto_nomempresa_and_more'),
        ('receta', '0004_delete_recetadetalle'),
        ('listaPrecio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estandarizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEstandarizador', models.CharField(max_length=50, verbose_name='id Estandarizador')),
                ('porcionesEstandar', models.CharField(max_length=50, verbose_name='Porciones Estandar')),
                ('nomListaPrecio', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Nombre Lista Precio')),
                ('nomCentroCostos', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Nombre Centro Costos')),
                ('nomReceta', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Nombre Receta')),
                ('codCentroCostos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='centroCostos.centrocosto', verbose_name='Cod Centro Costos')),
                ('codIngrediente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ingrediente.ingrediente', verbose_name='Cod Ingrediente')),
                ('codListaPrecio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listaPrecio.listaprecio', verbose_name='Cod Lista Precio')),
                ('codReceta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='receta.receta', verbose_name='Cod Receta')),
            ],
            options={
                'verbose_name': 'Estandarizador',
                'verbose_name_plural': 'Estandarizadores',
            },
        ),
    ]
