# Generated by Django 4.1.1 on 2023-06-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estandarizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEstandarizador', models.CharField(max_length=50, verbose_name='id Estandarizador')),
                ('porcionesEstandar', models.CharField(max_length=50, verbose_name='Porciones Estandar')),
                ('nomListaPrecio', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Nombre Lista Precio')),
                ('nomCentroCostos', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Nombre Centro Costos')),
                ('nomReceta', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Nombre Receta')),
            ],
            options={
                'verbose_name': 'Estandarizador',
                'verbose_name_plural': 'Estandarizadores',
            },
        ),
    ]
