# Generated by Django 4.1.2 on 2023-02-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroCostos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centrocosto',
            name='nomEmpresa',
        ),
        migrations.AlterField(
            model_name='centrocosto',
            name='nomCentroCostos',
            field=models.CharField(max_length=50, verbose_name='Nombre Centro de Costos'),
        ),
    ]
