# Generated by Django 4.1.1 on 2023-07-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Invitado', 'Invitado')], default='Invitado', max_length=13, verbose_name='Rol'),
        ),
    ]
