# Generated by Django 4.1.2 on 2022-10-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_rol_alter_usuario_clave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numeroDocumento',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número Documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoDocumento',
            field=models.CharField(choices=[('C.C', 'Cédula de Ciudadanía'), ('C.E', 'Cédula de Extranjería'), ('P.A', 'Otro Tipo de Documento')], default='C.C', max_length=20, verbose_name='Tipo Documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.CharField(choices=[('usuario', 'Usuario Estandar'), ('admin', 'Administrador')], default='usuario', max_length=20, verbose_name='Tipo Usuario'),
        ),
    ]
