# Generated by Django 4.1.1 on 2022-11-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_numerodocumento_usuario_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Super', 'Super'), ('Invitado', 'Invitado')], default='Invitado', max_length=20, verbose_name='Tipo Usuario'),
        ),
    ]
