# Generated by Django 4.1.1 on 2023-05-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_tipousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='clave',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombreUsuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoDocumento',
            field=models.CharField(choices=[('C.C', 'Cédula de Ciudadanía'), ('C.E', 'Cédula de Extranjería'), ('P.A', 'Pasaporte')], default='C.C', max_length=4, verbose_name='Tipo Documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Estandar', 'Estandar'), ('Invitado', 'Invitado')], default='Invitado', max_length=13, verbose_name='Rol'),
        ),
    ]
