# Generated by Django 4.1.1 on 2023-06-01 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_usuario_clave_remove_usuario_nombreusuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='tipoUsuario',
            new_name='rol',
        ),
    ]
