# Generated by Django 4.1.1 on 2023-06-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codComponente', models.TextField(max_length=50, verbose_name='Código Componente')),
                ('nomComponente', models.TextField(max_length=50, verbose_name='Nombre Componente')),
            ],
        ),
    ]
