# Generated by Django 4.1.1 on 2023-06-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codIngrediente', models.CharField(max_length=50, verbose_name='Codigo Ingrediente')),
                ('nomIngrediente', models.CharField(max_length=50, verbose_name='Nombre Ingrediente')),
                ('unidadMedida', models.CharField(max_length=50, verbose_name='Unidad de Medida')),
                ('costoIngrediente', models.CharField(max_length=50, verbose_name='Costo Ingrediente')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
            },
        ),
    ]
