# Generated by Django 4.1.2 on 2023-02-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingrediente', '0004_ingrediente_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='cantidadMateriaPrima',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='costoIngrediente',
            field=models.CharField(default=2, max_length=50, verbose_name='Costo Ingrediente'),
            preserve_default=False,
        ),
    ]
