# Generated by Django 4.1.2 on 2023-02-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingrediente', '0006_alter_ingrediente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
