# Generated by Django 4.1.5 on 2023-05-30 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingrediente', '0007_alter_ingrediente_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingrediente',
            options={'verbose_name': 'Ingrediente', 'verbose_name_plural': 'Ingredientes'},
        ),
    ]
